function [ output_args ] = report_single( input_args )

    hpanel4 = findobj('Tag', 'panel4');
    data = getappdata(hpanel4, 'reportSingle');
    
    hFigure = figure( 'Name', 'Realization report', ...
        'NumberTitle', 'off', ...
        'MenuBar','none',...
        'Toolbar','figure',...
        'Units', 'pixels', ...
        'Position', [100 100 900 600],...
        'Resize', 'off', ...
        'Visible','off', ...
        'Tag', 'realiz');
    
    panel5 = uipanel(hFigure, 'Title', 'Realization history', ...
        'Units', 'pixels', ...
        'Position', [20 20 560 570], ...
        'Tag', 'panel5');
    
    panel6 = uipanel(hFigure, 'Title', 'Indicators', ...
        'Units', 'pixels', ...
        'Position', [595 20 290 570], ...
        'Tag', 'panel6');
    
    gui.plot_history(panel5, data)
    
    hFigure.Visible = 'on';
    
end

