function varargout = gui()
% MYGUI Brief description of GUI.
%       Comments displayed at the command line in response 
%       to the help command. 

% (Leave a blank line following the help.)


%%  Initialization tasks
% http://www.mathworks.com/help/matlab/creating_guis/initializing-a-programmatic-gui.html

close all

gui_State = struct('gui_Name', mfilename, ...
                   'gui_OpeningFcn', @single_ui_OpeningFcn, ...
                   'gui_OutputFcn', @single_ui_OutputFcn, ...
                   'gui_LayoutFcn', [] , ...
                   'gui_Callback', [], ...
                   'window_props', []);

init(gui_State);

end

%%  Construct the components
% http://www.mathworks.com/help/matlab/creating_guis/creating-figures-for-programmatic-guis.html
% http://www.mathworks.com/help/matlab/creating_guis/adding-components-to-a-programmatic-gui.html

function init(gui_State)
    ss = get(0,'screensize');
    widthScreen = ss(3);
    heightScreen = ss(4);

    widthWindow = 900;
    heightWindow = 500;
    
    gui_State.window_props.wh = [widthWindow, heightWindow];
    
    %% Main window
    posVec = [  (widthScreen/2)-(widthWindow/2) , ...
                (heightScreen/2)-(heightWindow/2) , ...
                widthWindow , ...
                heightWindow];

    hMainFigure = figure( 'MenuBar','none',...
                          'Toolbar','none',...
                          'Units', 'pixels', ...
                          'Position', posVec,...
                          'Visible','off');
    
    hMainFigure.Visible = 'on';
    
    %% Tabs
    margin = 20;
    tabGroup_posVec = [ margin, ...
                        margin, ...
                        (widthWindow-2*margin), ...
                        (heightWindow-2*margin)];
                    
    tabgp = uitabgroup(hMainFigure, 'Units', 'pixels', ...
                                    'Position', tabGroup_posVec);
    
    tab1 = uitab(tabgp,'Title','Experiment');
    tab2 = uitab(tabgp,'Title','Results');
    
    %% Panels
    
    % Panels for tab1
    width_panels = 815;
    
    panel1 = uipanel(tab1,  'Title', 'Select experiments folder', ...
                            'Units', 'pixels', ...
                            'Position', [20 350 width_panels 70], ...
                            'Tag', 'panel1');
    
    panel2 = uipanel(tab1,  'Title', 'Choose experiment', ...
                            'Units', 'pixels', ...
                            'Position', [20 110 width_panels 230], ...
                            'Tag', 'panel2');
    
    panel3 = uipanel(tab1,  'Title', 'Run experiment', ...
                            'Units', 'pixels', ...
                            'Position', [20 20 width_panels 80], ...
                            'Tag', 'panel3');
    
    % Panels for tab2
    
    %% Buttons
    
    button1 = uicontrol(panel1, ...
                        'Style', 'pushbutton', ...
                        'String', 'Browse...',...
                        'Position', [20 15 80 30],...
                        'Callback', @button1_callback, ...
                        'Tag', 'button1');

    button2 = uicontrol(panel2, ...
                        'Style', 'pushbutton', ...
                        'String', 'Set custom parameters',...
                        'Position', [20 15 150 30],...
                        'Callback', [], ...
                        'Tag', 'button2');
    
    button3 = uicontrol(panel3, ...
                        'Style', 'pushbutton', ...
                        'String', 'Run experiment', ...
                        'Position', [20 15 150 30],...
                        'Callback', [], ...
                        'Tag', 'button3');
    
    %% Edit text
                    
    edit1 = uicontrol(  panel1,...
                        'Style','edit',...
                        'String','Enter directory path...',...
                        'Position',[120 17 670 28], ...
                        'Tag', 'edit1');

    %% Static text
    
    static1 = uicontrol(panel2, ...
                        'Style','text',...
                        'BackgroundColor', 'white', ...
                        'String','Select a data set.',...
                        'HorizontalAlignment', 'left', ...
                        'Position',[350 20 440 180]);
    %% Tables
    
    table1 = uitable(   panel2, ...
                        'Data', [],... 
                        'ColumnName', {'Name', 'Type'},...
                        'ColumnEditable', [false false], ...
                        'Position', [20 60 300 140]);
    
    %% Progress bar
    
    ax1 = axes( 'Units', 'pixels', ...
                'Position', [190 20 600 10], ...
                'XLim',[0 1], ...
                'YLim',[0 1],...
                'XTick',[], ...
                'YTick',[],...
                'Color','white',...
                'Box', 'on', ...
                'XColor', [0.4314  0.4314  0.4314],...
                'YColor', [0.4314  0.4314  0.4314],...
                'Parent', panel3);
    
    patch(  [0  0  0  0], [0  0  1  1], [0.4392  0.7882  0.3686],...
            'Parent', ax1, ...
            'EdgeColor', 'none', ...
            'Tag', 'progressPatch');
    
    %% Finilize window setup
    
    hMainFigure.Visible = 'on';
    
end

%%  Initialization tasks
% http://www.mathworks.com/help/matlab/creating_guis/initializing-a-programmatic-gui.html


%%  Callbacks for MYGUI
% http://www.mathworks.com/help/matlab/creating_guis/adding-components-to-a-programmatic-gui.html
function button1_callback(hObject, callbackdata)
% Browse folder for experiments
    
    p = uigetdir();
    
    h = findobj('Tag','edit1');
    h.String = p;
end

%%  Utility functions for MYGUI

function str = getPathField()
% Get path string of experiments folder

    h = findobj('Tag','edit1');
    str = h.String;
end

function updateProgressBar(value)
% Updates the progress bar to the value parameter
    p = findobj('Tag','progressPatch');
    p.XData(2:3) = value;
end
